#!/bin/bash

# Remove build artifacts
rm -rf Data/System/Source/obj

# Compile the project
mcs -optimize+ -unsafe -t:exe -out:world_dev.exe -nowarn:219,414 -d:NEWTIMERS -d:NEWPARENT -d:MONO -reference:System.Drawing -recurse:"Data/System/Source/*.cs"

# Run the compiled executable
mono world_dev.exe

